export default [
  { property: 'og:image', content: 'http://codeacola.com/images/og.jpg' },
  { property: 'og:image', content: 'http://codeacola.com/images/og.jpg' },
  { property: 'og:image:secure_url', content: 'https://codeacola.com/images/og.jpg' },
  { property: 'og:image:type', content: 'image/png' },
  { property: 'og:image:width', content: '1200' },
  { property: 'og:image:height', content: '630' },
  { property: 'og:description', content: 'code@cola - Javascript Projects' },
  { property: 'og:url', content: 'https://codeacola.com' },
  { property: 'og:title', content: 'code@cola - Javascript Projects' },
  { property: 'og:site_name', content: 'code@cola - Javascript Projects' },
  { name: 'twitter:title', content: 'code@cola - Javascript Projects' },
  { name: 'twitter:description', content: ' Open source javascript projects for developers.' },
  { name: 'twitter:image', content: 'https://codeacola.com/images/og.jpg' },
  { name: 'twitter:card', content: 'summary_large_image' },
  { name: 'twitter:site', content: '@codeacola' },
  { name: 'twitter:image:alt', content: 'code@cola - Javascript Projects' },
  { charset: 'utf-8' },
  { 'http-equiv': 'X-UA-Compatible', content: 'IE=edge' },
  { 'http-equiv': 'Cache-Control', content: 'no-cache, no-store, must-revalidate' },
  { 'http-equiv': 'Pragma', content: 'no-cache' },
  { 'http-equiv': 'Expires', content: '0' },
  { name: 'description', content: 'Open source javascript projects for developers.' },
  { name: 'author', content: 'code@cola' },
  {
    name: 'keywords',
    content: 'code, development, javascript, developers, projects, open source, git, github, vue, vuejs, gridsome',
  },
  { name: 'robots', content: 'index,follow' },
  {
    name: 'viewport',
    content: 'width=device-width, height=device-height, initial-scale=1, maximum-scale=1, user-scalable=no'
  },
  { name: 'apple-mobile-web-app-capable', content: 'yes' },
  { name: 'apple-mobile-web-app-status-bar-style', content: 'black' },
  { name: 'theme-color', content: '#291e64' },
  { name: 'msapplication-navbutton-color', content: '#291e64' },
  { name: 'mobile-web-app-capable', content: 'yes' },
];
